test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws_access_key_id %>
  secret_access_key: <%= Rails.application.credentials.aws_secret_access_key %>
  region: us-east-2
  bucket: raccoon-status-<%= Rails.env %>
